google:
  type: GOOGLE
  client_id: performance-test-google
  client_secret: performance-test-google
  signup_redirect_url: performance-test-google
  login_redirect_url: performance-test-google
  access_token_api: http://13.124.232.206:8080/oauth2/access_token
  profile_api: http://13.124.232.206:8080/oauth2/profile

kakao:
  type: KAKAO
  client_id: performance-test-oauth-kakao
  client_secret: performance-test-oauth-kakao
  signup_redirect_url: performance-test-oauth-kakao
  login_redirect_url: performance-test-oauth-kakao
  access_token_api: performance-test-oauth-kakao
  profile_api: performance-test-oauth-kakao

naver:
  type: NAVER
  client_id: performance-test-oauth-naver
  client_secret: performance-test-oauth-naver
  signup_redirect_url: performance-test-oauth-naver
  login_redirect_url: performance-test-oauth-naver
  access_token_api: performance-test-oauth-naver
  profile_api: performance-test-oauth-naver

spring:
  datasource:
    url: jdbc:mysql://13.209.87.3:8080/tyf?useSSL=false&ServerTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: tyf
    password: password
  mail:
    username: thank.you.for.tyf@gmail.com
    password: tyfPassword1!

jwt:
  secreteKey: tyf-prod-jwt-secretKey
  expire-length: 6000000

iamport:
  rest_api_key: performance-test-rest-api-key
  rest_api_secret: performance-test-rest-api-secret

admin:
  id: tyf
  password: tyfPassword1!
  
aes:
  secret:
    aasdtdj123fydf6dq=edja89wptro3ds
